### ISSUE TITLE
Invalid player data error

### ISSUE THREAD

**Issue by Sunconure11** [DakotaPride/Effective-Regalia#1]
https://github.com/fzzyhmstrs/ai/issues/78

**Comment by DakotaPride** [comment]
@Sunconure11 What exactly are you doing before the error occurs? (are in the world? Loading up the game? etc.)

**Comment by Sunconure11** [comment]
Attempting to create a new world

**Comment by DakotaPride** [comment]
@Sunconure11 could you provide a full list of the mods you're using or the modpack that you're playing? It seems to work just fine normally when testing.

**Comment by Sunconure11** [comment]
It happens when Amethyst Imbuement is installed alongside it. Try that mod with it. I am also on Quilt.

**Comment by DakotaPride** [comment]
Hmmm, weird. I'm not sure entirely why this is happening, but I do currently plan to rework how Effective Regalia works, so I suggest for the time being removing Effective Regalia until 0.3 is released (no estimated time of release however, apologies for the issues)

**Comment by DakotaPride** [comment]
Try updating to 0.3.0 for 1.19.2, let me know if it still crashes! (I'm also about to upload the 1.20 version for 0.3.0 as well)

**Comment by Sunconure11** [comment]
Prepping to test now.

**Comment by Sunconure11** [comment]
Works.
