### ISSUE TITLE
Effective Regalia asking for a Trinkets version that isn't for my minecraft version

### ISSUE THREAD

**Issue by mistakeL** [DakotaPride/Effective-Regalia#2]
As the title says, Effective Regalia is asking for Trinkets version 3.7.0, however, I am playing on 1.19.3, and the latest version of Trinkets for 1.19.3 is version 3.5.1
[Uploading crash-2024-02-24_11.55.07.1276-quilt_loader.txt…]()

**Comment by DakotaPride** [comment]
Should be fixed now, let me know if there are any other issues or concerns! (on modrinth, waiting for Curseforge approval)
